spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        ddl-auto: validate
  datasource:
    username: postgres
    password: 111
    url: jdbc:postgresql://localhost:5432/pipeline
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: pipeline